import FooterLinks from "@/components/navbar/FooterLinks";
import { Navbar } from "@/components/navbar/Navbar";
import "@/styles/globals.scss";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";
import '@mantine/core/styles.css';
import { Notifications } from "@mantine/notifications";
import { Geist, Geist_Mono } from "next/font/google";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ujjwal pandey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ margin: "auto" }}>
        <MantineProvider>
          <Notifications />
          <Navbar />
          {children}  {/* Always CSR */}
          <FooterLinks />
        </MantineProvider>
      </body>
    </html>
  );
}
